#!/bin/bash
qsub Jquery/Jquery-0.sh
sleep 5m
qsub Jquery/Jquery-1.sh
sleep 5m
qsub Jquery/Jquery-2.sh
sleep 5m
qsub Jquery/Jquery-3.sh
sleep 5m
qsub Jquery/Jquery-4.sh
sleep 5m
qsub Jquery/Jquery-5.sh
sleep 5m
qsub Jquery/Jquery-6.sh
sleep 5m
qsub Jquery/Jquery-7.sh
sleep 5m
qsub Jquery/Jquery-8.sh
sleep 5m
qsub Jquery/Jquery-9.sh
sleep 5m
qsub Jquery/Jquery-10.sh
sleep 5m
qsub Jquery/Jquery-11.sh
sleep 5m
qsub Jquery/Jquery-12.sh
sleep 5m
qsub Jquery/Jquery-13.sh
sleep 5m
qsub Jquery/Jquery-14.sh
sleep 5m
qsub Jquery/Jquery-15.sh
sleep 5m
qsub Jquery/Jquery-16.sh
sleep 5m
qsub Jquery/Jquery-17.sh
sleep 5m
qsub Jquery/Jquery-18.sh
sleep 5m
qsub Jquery/Jquery-19.sh
sleep 5m
qsub Jquery/Jquery-20.sh
sleep 5m
qsub Jquery/Jquery-21.sh
sleep 5m
qsub Jquery/Jquery-22.sh
sleep 5m
qsub Jquery/Jquery-23.sh
sleep 5m
qsub Jquery/Jquery-24.sh
sleep 5m
qsub Jquery/Jquery-25.sh
sleep 5m
qsub Jquery/Jquery-26.sh
sleep 5m
qsub Jquery/Jquery-27.sh
sleep 5m
qsub Jquery/Jquery-28.sh
sleep 5m
qsub Jquery/Jquery-29.sh
sleep 5m
qsub Jquery/Jquery-30.sh
sleep 5m
qsub Jquery/Jquery-31.sh
sleep 5m
qsub Jquery/Jquery-32.sh
sleep 5m
qsub Jquery/Jquery-33.sh
sleep 5m
qsub Jquery/Jquery-34.sh
sleep 5m
qsub Jquery/Jquery-35.sh
sleep 5m
qsub Jquery/Jquery-36.sh
sleep 5m
qsub Jquery/Jquery-37.sh
sleep 5m
qsub Jquery/Jquery-38.sh
sleep 5m
qsub Jquery/Jquery-39.sh
sleep 5m
qsub Jquery/Jquery-40.sh
sleep 5m
qsub Jquery/Jquery-41.sh
sleep 5m
qsub Jquery/Jquery-42.sh
sleep 5m
qsub Jquery/Jquery-43.sh
sleep 5m
qsub Jquery/Jquery-44.sh
sleep 5m
qsub Jquery/Jquery-45.sh
sleep 5m
qsub Jquery/Jquery-46.sh
sleep 5m
qsub Jquery/Jquery-47.sh
sleep 5m
qsub Jquery/Jquery-48.sh
sleep 5m
qsub Jquery/Jquery-49.sh
sleep 5m
qsub Jquery/Jquery-50.sh
sleep 5m
qsub Jquery/Jquery-51.sh
sleep 5m
qsub Jquery/Jquery-52.sh
sleep 5m
qsub Jquery/Jquery-53.sh
sleep 5m
qsub Jquery/Jquery-54.sh
sleep 5m
qsub Jquery/Jquery-55.sh
sleep 5m
qsub Jquery/Jquery-56.sh
sleep 5m
qsub Jquery/Jquery-57.sh
sleep 5m
qsub Jquery/Jquery-58.sh
sleep 5m
qsub Jquery/Jquery-59.sh
sleep 5m
