#!/bin/bash
qsub Lodash/Lodash-0.sh
sleep 1m
qsub Lodash/Lodash-1.sh
sleep 1m
qsub Lodash/Lodash-3.sh
sleep 1m
qsub Lodash/Lodash-6.sh
sleep 1m
qsub Lodash/Lodash-7.sh
sleep 1m
qsub Lodash/Lodash-9.sh
sleep 1m
qsub Lodash/Lodash-16.sh
sleep 1m
qsub Lodash/Lodash-19.sh
sleep 1m
qsub Lodash/Lodash-21.sh
sleep 1m
qsub Lodash/Lodash-30.sh
sleep 1m
qsub Lodash/Lodash-33.sh
sleep 1m
qsub Lodash/Lodash-34.sh
sleep 1m
qsub Lodash/Lodash-36.sh
sleep 1m
qsub Lodash/Lodash-39.sh
sleep 1m
qsub Lodash/Lodash-47.sh
sleep 1m
qsub Lodash/Lodash-50.sh
sleep 1m
qsub Lodash/Lodash-58.sh