#!/bin/bash
qsub Node-browserrify/Node-browserrify-1.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-2.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-3.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-4.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-5.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-6.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-7.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-8.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-9.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-10.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-11.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-12.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-13.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-14.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-15.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-16.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-17.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-18.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-19.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-20.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-21.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-22.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-23.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-24.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-25.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-26.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-27.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-28.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-29.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-30.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-31.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-32.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-33.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-34.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-35.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-36.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-37.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-38.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-39.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-40.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-41.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-42.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-43.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-44.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-45.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-46.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-47.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-48.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-49.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-50.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-51.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-52.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-53.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-54.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-55.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-56.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-57.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-58.sh
sleep 1m
qsub Node-browserrify/Node-browserrify-59.sh
sleep 1m
