language: node_js
node_js:
  - "4"
  - "6"

# Use faster Docker architecture on Travis.
sudo: false

script:        npm test
# TODO: coverage
# after_success: npm run coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dd893be75c6b9908987d
    on_success: change
    on_failure: always
    on_start:   never
