#!/bin/bash
qsub minimist/minimist-0.sh
sleep 0.5
qsub minimist/minimist-1.sh
sleep 0.5
qsub minimist/minimist-2.sh
sleep 0.5
qsub minimist/minimist-3.sh
sleep 0.5
qsub minimist/minimist-4.sh
sleep 0.5
qsub minimist/minimist-5.sh
sleep 0.5
qsub minimist/minimist-6.sh
sleep 0.5
qsub minimist/minimist-7.sh
sleep 0.5
qsub minimist/minimist-8.sh
sleep 0.5
qsub minimist/minimist-9.sh
sleep 0.5
qsub minimist/minimist-10.sh
sleep 0.5
qsub minimist/minimist-11.sh
sleep 0.5
qsub minimist/minimist-12.sh
sleep 0.5
qsub minimist/minimist-13.sh
sleep 0.5
qsub minimist/minimist-14.sh
sleep 0.5
qsub minimist/minimist-15.sh
sleep 0.5
qsub minimist/minimist-16.sh
sleep 0.5
qsub minimist/minimist-17.sh
sleep 0.5
qsub minimist/minimist-18.sh
sleep 0.5
qsub minimist/minimist-19.sh
sleep 0.5
qsub minimist/minimist-20.sh
sleep 0.5
qsub minimist/minimist-21.sh
sleep 0.5
qsub minimist/minimist-22.sh
sleep 0.5
qsub minimist/minimist-23.sh
sleep 0.5
qsub minimist/minimist-24.sh
sleep 0.5
qsub minimist/minimist-25.sh
sleep 0.5
qsub minimist/minimist-26.sh
sleep 0.5
qsub minimist/minimist-27.sh
sleep 0.5
qsub minimist/minimist-28.sh
sleep 0.5
qsub minimist/minimist-29.sh
sleep 0.5
qsub minimist/minimist-30.sh
sleep 0.5
qsub minimist/minimist-31.sh
sleep 0.5
qsub minimist/minimist-32.sh
sleep 0.5
qsub minimist/minimist-33.sh
sleep 0.5
qsub minimist/minimist-34.sh
sleep 0.5
qsub minimist/minimist-35.sh
sleep 0.5
qsub minimist/minimist-36.sh
sleep 0.5
qsub minimist/minimist-37.sh
sleep 0.5
qsub minimist/minimist-38.sh
sleep 0.5
qsub minimist/minimist-39.sh
sleep 0.5
qsub minimist/minimist-40.sh
sleep 0.5
qsub minimist/minimist-41.sh
sleep 0.5
qsub minimist/minimist-42.sh
sleep 0.5
qsub minimist/minimist-43.sh
sleep 0.5
qsub minimist/minimist-44.sh
sleep 0.5
qsub minimist/minimist-45.sh
sleep 0.5
qsub minimist/minimist-46.sh
sleep 0.5
qsub minimist/minimist-47.sh
sleep 0.5
qsub minimist/minimist-48.sh
sleep 0.5
qsub minimist/minimist-49.sh
sleep 0.5
qsub minimist/minimist-50.sh
sleep 0.5
qsub minimist/minimist-51.sh
sleep 0.5
qsub minimist/minimist-52.sh
sleep 0.5
qsub minimist/minimist-53.sh
sleep 0.5
qsub minimist/minimist-54.sh
sleep 0.5
qsub minimist/minimist-55.sh
sleep 0.5
qsub minimist/minimist-56.sh
sleep 0.5
qsub minimist/minimist-57.sh
sleep 0.5
qsub minimist/minimist-58.sh
sleep 0.5
qsub minimist/minimist-59.sh
sleep 0.5
